export const FEATURED_WORK = [
  {
    title: "I Built a Chatbot That Found Our Hidden Money-Losing Products",
    description:
      "A Telegram AI agent that queries a live ERP in plain language — three questions in, it surfaces which products quietly lose money and charts it.",
    href: "/work/agentic-erp",
    tags: ["LLM Agent", "Text2SQL", "Data Viz"],
    imageSrc: "/video/agentic-erp-thumb.jpg",
    imageAlt: "Scatter plot generated by the ERP AI agent showing revenue vs. gross margin, flagging hidden loss-making products",
  },
  {
    title: "This AI Reads a Freezer Photo and Tells You What's Wrong",
    description:
      "A YOLO model reads a single freezer photo and scores planogram compliance — the same audit that used to take a manual walk-through.",
    href: "/work/vision-kpi",
    tags: ["YOLOv11", "Computer Vision", "KPI Scoring"],
    imageSrc: "/demo/vision-kpi/annotated/store-04-sku.jpg",
    imageAlt: "YOLO model detecting SKUs inside an ice cream freezer planogram, with confidence scores overlaid",
  },
] as const;

export const OTHER_WORK = [
  {
    title: "This AI Compares Two Packaging Designs and Circles Exactly What Changed",
    description:
      "A computer vision tool that pixel-diffs two packaging design files and flags exactly what changed — built to catch the one edit a tired eye misses across thousands of revisions.",
    href: "/work/packaging-diff",
    tags: ["Computer Vision", "OpenCV", "Image Diffing"],
    imageSrc: "/demo/packaging-diff/thumb.jpg",
    imageAlt: "Packaging design proof for TOP Kopi Susu Gula with a price tag added in a revision",
  },
  {
    title: "This AI Stops Half-Empty Pallets at the Warehouse Door",
    description:
      "A YOLO model watches an existing CCTV feed and classifies every pallet as full or not-full in real time — alarming before an incomplete one gets counted as stock.",
    href: "/work/pallet-detection",
    tags: ["YOLO", "Computer Vision", "Real-time Detection"],
    imageSrc: "/video/pallet-thumb.jpg",
    imageAlt: "CCTV feed with a YOLO model labeling warehouse pallets as pallet_full or pallet_not_full in real time",
  },
  {
    title: "This AI Catches Underperforming New Product Launches Before SCM Has To",
    description:
      "A pipeline that fills a demand-tracking sheet straight from BigQuery/SAP using the Supply Chain team's own formula, and an AI bot that can be asked directly which launches are falling behind.",
    href: "/work/npd-demand-automation",
    tags: ["BigQuery", "LLM Agent", "Automation"],
    imageSrc: "/demo/npd-automation/thumb.jpg",
    imageAlt: "Chat bot analyzing the worst-performing new product launches, with product identities redacted",
  },
] as const;
